[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 256

[invariant]
fail_on_revert = true
runs = 256
depth = 500

remapping = ["@openzeppelin/contracts = /lib/openzeppelin-contracts/contracts"]

solc = "0.8.22"

gas_reports = ["MarketService"]

via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
